googleAnalytics = "G-GWCP47ZZMB"

footer_newsletter_form_action = "https://formspree.io/f/mwkyqggo"





# 404 error customization
[params.error404]
heading = "Page couldn't be found"
text = "Please visit [homepage](/)"


########################### social links ############################
[[social]]
link = "https://www.youtube.com/channel/UCkuFpIkpvM4-OhJxoNocVQw"
icon = "/img/youtube.svg"

[[social]]
link = "https://www.linkedin.com/company/64686034/"
icon = "/img/linkedin.svg"


