baseURL = "/"
defaultContentLanguage = "en"
languageCode = "en-us"
theme = "ydigital"
title = "y.digital"
[languages.en]
languageName = "English"
title = "y.digital"
weight = 1
[languages.nl]
googleAnalytics = "G-GWCP47ZZMB"
languageName = "Dutch"
title = "y.digital"
weight = 2
