baseURL = "/"
defaultContentLanguage = "en"
languageCode = "en-us"
theme = "ydigital"
title = "y.digital"
googleAnalytics = "G-GWCP47ZZMB"

[languages.en]
languageName = "English"
title = "y.digital"
weight = 1


[languages.nl]
languageName = "Dutch"
title = "y.digital"
weight = 2



[[languages.en.menu.main]]
identifier = "approach"
name = "approach"
title = "approach"
url = "/approach/"
pageRef = "/approach"
weight = 10
[[languages.en.menu.main]]
identifier = "solutions"
name = "solutions"
title = "solutions"
url = "/solutions/"
pageRef = "/solutions"
weight = 20
	[[languages.en.menu.main]]
	identifier = "conversational-ai"
	parent = "solutions"
	name = "conversational ai"
	title = "conversational ai"
	url = "/solutions/conversational-ai/"
	pageRef = "/solutions/conversational-ai"
	weight = 22
	[[languages.en.menu.main]]
	identifier = "intelligent-document-processing"
	parent = "solutions"
	name = "intelligent document processing"
	title = "intelligent document processing"
	url = "/solutions/intelligent-document-processing/"
	pageRef = "/solutions/intelligent-document-processing"
	weight = 24
[[languages.en.menu.main]]
identifier = "services"
name = "services"
title = "services"
url = "/services/"
pageRef = "/services"
weight = 30
[[languages.en.menu.main]]
identifier = "company"
name = "company"
title = "company"
url = "/company/"
pageRef = "/company"
weight = 40
	[[languages.en.menu.main]]
	identifier = "careers"
	parent = "company"
	name = "careers"
	title = "careers"
	url = "/company/careers/"
	pageRef = "/company/careers"
	weight = 42
	[[languages.en.menu.main]]
	identifier = "shared-knowledge"
	parent = "company"
	name = "shared knowledge"
	title = "shared knowledge"
	url = "/company/shared-knowledge/"
	pageRef = "/company/shared-knowledge"
	weight = 44
	[[languages.en.menu.main]]
	identifier = "faq"
	parent = "company"
	name = "faq"
	title = "faq"
	url = "/company/faq/"
	pageRef = "/company/faq"
	weight = 46
[[languages.en.menu.main]]
identifier = "contact"
name = "contact"
title = "contact"
url = "/contact/"
pageRef = "/contact"
weight = 50


[[languages.nl.menu.main]]
identifier = "approach"
name = "aanpak"
title = "aanpak"
url = "/nl/approach/"
pageRef = "/approach"
weight = 10
[[languages.nl.menu.main]]
identifier = "solutions"
name = "oplossingen"
title = "oplossingen"
url = "/nl/solutions/"
pageRef = "/solutions"
weight = 20
	[[languages.nl.menu.main]]
	identifier = "conversational-ai"
	parent = "solutions"
	name = "conversational ai"
	title = "conversational ai"
	url = "/nl/solutions/conversational-ai/"
	pageRef = "/solutions/conversational-ai"
	weight = 22
	[[languages.nl.menu.main]]
	identifier = "intelligent-document-processing"
	parent = "solutions"
	name = "intelligent document processing"
	title = "intelligent document processing"
	url = "/nl/solutions/intelligent-document-processing/"
	pageRef = "/solutions/intelligent-document-processing"
	weight = 24
[[languages.nl.menu.main]]
identifier = "services"
name = "diensten"
title = "diensten"
url = "/nl/services/"
pageRef = "/services"
weight = 30
[[languages.nl.menu.main]]
identifier = "company"
name = "bedrijf"
title = "bedrijf"
url = "/nl/company/"
pageRef = "/company"
weight = 40
	[[languages.nl.menu.main]]
	identifier = "careers"
	parent = "company"
	name = "careers"
	title = "careers"
	url = "/nl/company/careers/"
	pageRef = "/company/careers"
	weight = 42
	[[languages.nl.menu.main]]
	identifier = "shared-knowledge"
	parent = "company"
	name = "shared knowledge"
	title = "shared knowledge"
	url = "/nl/company/shared-knowledge/"
	pageRef = "/company/shared-knowledge"
	weight = 44
	[[languages.nl.menu.main]]
	identifier = "faq"
	parent = "company"
	name = "faq"
	title = "faq"
	url = "/nl/company/faq/"
	pageRef = "/company/faq"
	weight = 46
[[languages.nl.menu.main]]
identifier = "contact"
name = "contact"
title = "contact"
url = "/nl/contact/"
pageRef = "/contact"
weight = 50





[[languages.en.menu.footer]]
identifier = "home"
name = "Home"
url = "/"
pageRef = "/"
weight = 1

[[languages.en.menu.footer]]
identifier = "approach"
name = "Approach"
url = "/approach/"
pageRef = "/approach"
weight = 10
[[languages.en.menu.footer]]
identifier = "solutions"
name = "Solutions"
url = "/solutions/"
pageRef = "/solutions"
weight = 20
	[[languages.en.menu.footer]]
	identifier = "conversational-ai"
	parent = "solutions"
	name = "Conversational AI"
	url = "/solutions/conversational-ai/"
	pageRef = "/solutions/conversational-ai"
	weight = 22
	[[languages.en.menu.footer]]
	identifier = "intelligent-document-processing"
	parent = "solutions"
	name = "Intelligent Document Processing"
	url = "/solutions/intelligent-document-processing/"
	pageRef = "/solutions/intelligent-document-processing"
	weight = 24
[[languages.en.menu.footer]]
identifier = "services"
name = "Services"
url = "/services/"
pageRef = "/services"
weight = 30
[[languages.en.menu.footer]]
identifier = "company"
name = "Company"
url = "/company/"
pageRef = "/company"
weight = 40
	[[languages.en.menu.footer]]
	identifier = "careers"
	parent = "company"
	name = "Careers"
	url = "/company/careers/"
	pageRef = "/company/careers"
	weight = 42
	[[languages.en.menu.footer]]
	identifier = "shared-knowledge"
	parent = "company"
	name = "Shared knowledge"
	url = "/company/shared-knowledge/"
	pageRef = "/company/shared-knowledge"
	weight = 44
	[[languages.en.menu.footer]]
	identifier = "faq"
	parent = "company"
	name = "FAQ"
	url = "/company/faq/"
	pageRef = "/company/faq"
	weight = 46
[[languages.en.menu.footer]]
identifier = "contact"
name = "Contact"
url = "/contact/"
pageRef = "/contact"
weight = 50



[[languages.nl.menu.footer]]
identifier = "home"
name = "Home"
url = "/nl/"
pageRef = "/"
weight = 1

[[languages.nl.menu.footer]]
identifier = "approach"
name = "Aanpak"
url = "/nl/approach/"
pageRef = "/approach"
weight = 10
[[languages.nl.menu.footer]]
identifier = "solutions"
name = "Oplossingen"
url = "/nl/solutions/"
pageRef = "/solutions"
weight = 20
	[[languages.nl.menu.footer]]
	identifier = "conversational-ai"
	parent = "solutions"
	name = "Conversational AI"
	url = "/nl/solutions/conversational-ai/"
	pageRef = "/solutions/conversational-ai"
	weight = 22
	[[languages.nl.menu.footer]]
	identifier = "intelligent-document-processing"
	parent = "solutions"
	name = "Intelligent Document Processing"
	url = "/nl/solutions/intelligent-document-processing/"
	pageRef = "/solutions/intelligent-document-processing"
	weight = 24
[[languages.nl.menu.footer]]
identifier = "services"
name = "Diensten"
url = "/nl/services/"
pageRef = "/services"
weight = 30
[[languages.nl.menu.footer]]
identifier = "company"
name = "Bedrijf"
url = "/nl/company/"
pageRef = "/company"
weight = 40
	[[languages.nl.menu.footer]]
	identifier = "careers"
	parent = "company"
	name = "Careers"
	url = "/nl/company/careers/"
	pageRef = "/company/careers"
	weight = 42
	[[languages.nl.menu.footer]]
	identifier = "shared-knowledge"
	parent = "company"
	name = "Shared knowledge"
	url = "/nl/company/shared-knowledge/"
	pageRef = "/company/shared-knowledge"
	weight = 44
	[[languages.nl.menu.footer]]
	identifier = "faq"
	parent = "company"
	name = "FAQ"
	url = "/nl/company/faq/"
	pageRef = "/company/faq"
	weight = 46
[[languages.nl.menu.footer]]
identifier = "contact"
name = "Contact"
url = "/nl/contact/"
pageRef = "/contact"
weight = 50
